name: Semgrep Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run Semgrep Rules
        run: semgrep scan --config=auto
        continue-on-error: true
